[package]
name = "plantuml-export-zed"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[workspace]
members = ["crates/plantuml-export"]
default-members = ["."]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/dahuangggg/plantuml-export"

[lib]
crate-type = ["cdylib"]
path = "extension/src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
zed_extension_api = "0.7.0"
